# Uncomment the next line to define a global platform for your project
platform :ios, '12.3'

target 'Movie Sessions App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie Sessions App
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod "youtube-ios-player-helper", "~> 0.1.4"
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
end
